ALTER TABLE PASSPORTS
ADD SERIES_NUMBER VARCHAR;

UPDATE PASSPORTS SET SERIES_NUMBER = CONCAT(SERIES, ' ', NUMBER);

SELECT* FROM PASSPORTS;

ALTER TABLE PASSPORTS
DROP COLUMN SERIES;

ALTER TABLE PASSPORTS
DROP COLUMN NUMBER;